# This file was generated by GoReleaser. DO NOT EDIT.
class Fsrpl < Formula
  desc "fsrpl is CloudFirestore replication tool."
  homepage "https://github.com/matsu0228/fsrpl"
  version "0.0.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/matsu0228/fsrpl/releases/download/v0.0.4/fsrpl_0.0.4_darwin_amd64.tar.gz"
    sha256 "ee989c554973a4f3cefe26813ca35165c2a93e8c0794c0da23b1fd46adfff7ec"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/matsu0228/fsrpl/releases/download/v0.0.4/fsrpl_0.0.4_linux_amd64.tar.gz"
      sha256 "2d701ca87c618b9d44426f138db5afd953fb05bf1be4e5314f89e9498ce4a25a"
    end
  end

  def install
    bin.install Dir['fsrpl']
    zsh_completion.install "misc/completions/zsh/_fsrpl"
  end

  test do
    system "#{bin}/fsrpl"
  end
end
