# This file was generated by GoReleaser. DO NOT EDIT.
class Fsrpl < Formula
  desc "fsrpl is CloudFirestore replication tool."
  homepage "https://github.com/matsu0228/fsrpl"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/matsu0228/fsrpl/releases/download/1.0.0/fsrpl_1.0.0_darwin_amd64.tar.gz"
    sha256 "8ba531867efe70ec04e9959bdb348088fdf935ec8cb9e2e8f97e78b170f6c20f"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/matsu0228/fsrpl/releases/download/1.0.0/fsrpl_1.0.0_linux_amd64.tar.gz"
      sha256 "40c7fce4106aedb63d824ebffd7e559480d103acefd87691ffacedc4fd76acce"
    end
  end

  def install
    bin.install "fsrpl"
  end

  test do
    system "#{bin}/fsrpl"
  end
end
